name: "[Bug Report]"
description: Create a report to help us fix it
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Bartek20
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs (content of the /logs/app.log file)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in."
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this form, you confirm that the data provided in it is correct, and you are not trying to waste our time.
      options:
        - label: I confirm and agree to contact me by pinging me in this thread in case of questions.
          required: true
